"""update_user_table

Revision ID: bb1343eb2c4d
Revises: 0f13063994a0
Create Date: 2025-04-01 17:52:56.629225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb1343eb2c4d'
down_revision: Union[str, None] = '0f13063994a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('login', sa.String(length=32), nullable=False))
    op.drop_index('ix_users_nickname', table_name='users')
    op.create_index(op.f('ix_users_nickname'), 'users', ['nickname'], unique=False)
    op.create_index(op.f('ix_users_login'), 'users', ['login'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_login'), table_name='users')
    op.drop_index(op.f('ix_users_nickname'), table_name='users')
    op.create_index('ix_users_nickname', 'users', ['nickname'], unique=1)
    op.drop_column('users', 'login')
    # ### end Alembic commands ###
